# footprint: [[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]
#0.128
#footprint: [ [-0.15,-0.12], [0.15,-0.12], [0.15,0.12], [-0.15,0.12] ]
# footprint: [ [-0.15,-0.11], [0.15,-0.11], [0.15,0.11], [-0.15,0.11] ]
footprint: [ [-0.13,-0.10], [0.13,-0.10], [0.13,0.10], [-0.13,0.10] ]
obstacle_range: 3.0  #4.0
raytrace_range: 3.5   #4.5

static_layer:
  enabled: true

inflation_layer:
  enabled: true
  inflation_radius: 0.08 #0.08
  cost_scaling_factor: 5   #10.0

obstacle_layer:
  enabled: true
  track_unknown_space: false
  combination_method: 1

  obstacle_range: 3.0  #4.0
  raytrace_range: 3.5   #4.5

  observation_sources: scan
  scan: {
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }