global_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.5   #0.5

  static_map: false
  update_frequency: 5   #5    #25
  publish_frequency: 5  #2     #20

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
