shutdown_costmaps: false

oscillation_distance: 0.2
oscillation_timeout: 2.0  #0.0
controller_frequency: 20.0  #20
controller_patience: 20.0  #15

planner_frequency: 5.0
planner_patience: 5.0
max_planning_retries: -1
conservative_reset_dist: 3.0
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"